<?php

// O. UITLEZEN VAN DE POST-ARRAY
$subject = $_POST['subject'];
$message = $_POST['message'];

// 1. CONNECTIE MAKEN MET DE DATABASE

// 2. KJKEN IN DE DATABASE EN ALLE MAILADRESSEN TEVOORSCHINN HALEN

// 3. LOOPJE WAARIN EEN BERICHT WORD VERZONDEN NAAR ALLE MAILADRSESSEN